In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob, os
pd.set_option('display.max_columns', None)

# Max Rows and columns
Exactly what it sounds like. This gives us the max rows and columns our of ALL our files

In [2]:
def getMaxColumnsAndRows():
    columns = []
    indexes = []
    for file in glob.glob(r'C:\Users\tjbro\Desktop\tab_list_.03\*'):
        df = pd.read_csv(file)
        df = df.set_index('Unnamed: 0')
        del(df.index.name)
        columns.append(list(df.columns))
        indexes.append(list(df.index))
    indexes = np.hstack(indexes)
    maxRows = list(np.unique(np.sort(indexes)))
    columns = np.hstack(columns)
    maxColumns = list(np.unique(np.sort(columns)))        
    return(maxColumns, maxRows)

In [3]:
def addColumns(df, maxColumns):
    df = df.loc[:, maxColumns].fillna(0)
    return(df)

In [9]:
def getNewDf(maxRows, maxColumns):
    data = np.zeros((len(maxRows), len(maxColumns)))
    newDf = pd.DataFrame(data, maxRows, maxColumns)
    for file in glob.glob(r'C:\Users\tjbro\Desktop\tab_list_.03\*'):
        df = pd.read_csv(file)
        df = df.set_index('Unnamed: 0')
        del(df.index.name)
        df = addColumns(df, maxColumns)
        for i in df.index:
            newDf.loc[i] += df.loc[i]
    return(newDf)

# def visitedPerIndividual(df, maxRows, maxColumns):
#     data = np.zeros((len(maxRows), len(maxColumns)))
#     newDf = pd.DataFrame(data, maxRows, maxColumns)
#     for file in glob.glob(r'C:\Users\tjbro\Desktop\tab_list_.03\*'):
#         df = pd.read_csv(file)
#         df = df.set_index('Unnamed: 0')
#         del(df.index.name)
#         for i in df.index:
#             display(df.loc[i].values, '\n and \n', newDf.loc[i].values)
#             newDf.loc[i] += df.loc[i]
#             display(newDf)
#     return(newDf)

In [13]:
def addRows(df, newDf, maxRows):
    if len(maxRows) == len(list(df.index)):
        return(df)
#    print('all rows', len(maxRows), 'current rows', len(list(df.index)))
    differentElements = set(maxRows).difference(list(df.index))
#    print(differentElements, len(differentElements))
    for i in differentElements:
        inhabitedLocations = newDf.loc[i].nonzero()[0]
#        print('inhabited locations\n', inhabitedLocations, 'length of them\n', len(inhabitedLocations))
        indexOfLocation = np.random.choice(len(inhabitedLocations), 1)
#        print('index of the location', indexOfLocation)
        newRow = np.zeros(len(list(df.columns)))
        newRow[inhabitedLocations[indexOfLocation]] = 1
        df.loc[i] = newRow 
    return(df)

In [6]:
def binaryValues(df):
    for i in df.index:
        seriesRow = df.loc[i]
        nonzeroEntries = seriesRow.nonzero()[0]
        actualEntryValues = []
        for j in nonzeroEntries:
            actualEntryValues.append(df.loc[i][j])
            df.loc[i][j] = 0
        #display(nonzeroEntries, array)
        df.loc[i][nonzeroEntries[np.argmax(actualEntryValues)]] = 1
    return(df)

In [7]:
def fullFunction():
    networkList = []
    maxColumns, maxRows = getMaxColumnsAndRows()
    newDf = getNewDf(maxRows, maxColumns)
    for file in glob.glob(r'C:\Users\tjbro\Desktop\tab_list_.03\*'):
        df = pd.read_csv(file)
        df = df.set_index('Unnamed: 0')
        del(df.index.name)
        df = addColumns(df, maxColumns)
        df = addRows(df, newDf, maxRows)        
        df = binaryValues(df)
        networkList.append(df.to_numpy())
    return(networkList)

In [14]:
networkList = fullFunction()
#print(np.array(networkList).shape)

{42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 12
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [2]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [4]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [1]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [1]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [1]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [3]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [6]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [3]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [1]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [4]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [3]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [12]
{42739} 1
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [2]
{42739} 1
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [1]
{42737, 42739} 2
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [3]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
{42737, 42739} 2
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [2]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [1]
{42737, 42739} 2
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [4]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
{42737, 42739} 2
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [4]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [3]
{42737, 42739} 2
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [3]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [0]
{42737, 42739, 41995} 3
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [0]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [1]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [1]
{42737, 42739, 41995} 3
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [0]

D:\Spyder\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead

inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [3]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [1]
{42737, 42739, 41995} 3
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [4]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [2]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [2]
{42737, 42739, 41995} 3
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [0]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [1]
{42737, 42739, 41995} 3
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [1]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [4]
{42737, 42739, 41995} 3
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [3]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [0]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [3]
{42737, 42739, 41995} 3
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [0]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [4]
{42737, 42739, 41995} 3
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [2]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [1]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [3]
{41995, 42737, 42738, 42739} 4
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [4]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [4]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [2]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [0]
{41995, 42737, 42738, 42739} 4
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [2]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [3]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [0]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [3]
{41995, 42737, 42738, 42739} 4
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [0]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [4]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [4]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [1]
{39879, 41992, 41994, 41995, 39886, 42711, 42737, 42738, 42739} 9
inhabited locations
 [10 11 12 20 21 22 23 31] length of them
 8
index of the location [3]
inhabited locations
 [10 11 20 21 22 23 31 32] length of them
 8
index of the location [2]
inhabited locations
 [21 22 23 31 32] length of them
 5
index of the location [0]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [0]
inhabited locations
 [12 21 22 23 24 31 32 33] length of them
 8
index of the location [5]
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [3]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [2]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [2]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
{41992, 41993, 41994, 41995, 39879, 39886, 42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 18
inhabited locations
 [10 11 20 21 22 23 31 32] length of them
 8
index of the location [3]
inhabited locations
 [ 6 11 21 22 23 31 32] length of them
 7
index of the location [1]
inhabited locations
 [21 22 23 31 32] length of them
 5
index of the location [3]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [0]
inhabited locations
 [10 11 12 20 21 22 23 31] length of them
 8
index of the location [4]
inhabited locations
 [12 21 22 23 24 31 32 33] length of them
 8
index of the location [0]
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [3]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [3]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [3]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [2]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [1]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [0]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [1]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [3]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [2]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [5]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [9]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [11]
{41992, 41993, 41994, 41995, 39879, 39886, 42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 18
inhabited locations
 [10 11 20 21 22 23 31 32] length of them
 8
index of the location [2]
inhabited locations
 [ 6 11 21 22 23 31 32] length of them
 7
index of the location [6]
inhabited locations
 [21 22 23 31 32] length of them
 5
index of the location [2]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [4]
inhabited locations
 [10 11 12 20 21 22 23 31] length of them
 8
index of the location [3]
inhabited locations
 [12 21 22 23 24 31 32 33] length of them
 8
index of the location [4]
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [1]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [4]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [1]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [0]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [2]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [5]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [0]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [2]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [1]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [3]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [6]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [9]
{41992, 41993, 41994, 41995, 39879, 39886, 42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 18
inhabited locations
 [10 11 20 21 22 23 31 32] length of them
 8
index of the location [6]
inhabited locations
 [ 6 11 21 22 23 31 32] length of them
 7
index of the location [0]
inhabited locations
 [21 22 23 31 32] length of them
 5
index of the location [4]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [3]
inhabited locations
 [10 11 12 20 21 22 23 31] length of them
 8
index of the location [0]
inhabited locations
 [12 21 22 23 24 31 32 33] length of them
 8
index of the location [6]
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [10]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [4]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [3]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [3]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [2]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [2]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [2]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [1]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [0]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [8]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [14]
{41992, 41993, 41994, 41995, 39879, 39886, 42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 18
inhabited locations
 [10 11 20 21 22 23 31 32] length of them
 8
index of the location [0]
inhabited locations
 [ 6 11 21 22 23 31 32] length of them
 7
index of the location [2]
inhabited locations
 [21 22 23 31 32] length of them
 5
index of the location [1]
inhabited locations
 [10 11 21 22 23] length of them
 5
index of the location [4]
inhabited locations
 [10 11 12 20 21 22 23 31] length of them
 8
index of the location [6]
inhabited locations
 [12 21 22 23 24 31 32 33] length of them
 8
index of the location [2]
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [7]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [3]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [1]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [4]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [0]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [0]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [2]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [5]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [2]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [6]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [8]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [6]
{42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 12
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [1]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [3]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [2]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [4]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [0]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [5]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [7]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [0]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [3]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [0]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [3]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [6]
{42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 12
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [6]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [0]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [4]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [0]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [1]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [4]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [4]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [4]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [2]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [5]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [7]
{42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 12
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [8]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [4]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [4]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [5]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [5]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [5]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [0]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [4]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [2]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [10]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [4]
{42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 12
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [6]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [4]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [1]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [2]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [3]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [1]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [3]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [5]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [0]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [5]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [10]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [8]
{42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 12
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [12]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [2]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [0]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [3]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [4]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [3]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [2]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [5]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [0]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [4]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [8]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [2]
{42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 12
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [8]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [0]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [3]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [3]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [0]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [4]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [3]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [2]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [0]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [7]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [2]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [10]
{42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 12
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [2]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [4]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [2]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [2]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [3]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [6]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [8]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6
index of the location [4]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [2]
inhabited locations
 [ 8 15 16 17 18 19 28 29] length of them
 8
index of the location [3]
inhabited locations
 [ 2  3 39 40 46 47 53 54 55 65 66 67] length of them
 12
index of the location [4]
inhabited locations
 [35 36 37 38 39 40 41 42 43 47 48 49 56 57 58] length of them
 15
index of the location [1]
{42711, 42328, 42737, 42738, 42739, 42740, 42741, 42742, 42743, 42744, 42745, 42746} 12
inhabited locations
 [35 36 37 38 40 41 42 43 46 47 48 49 50 56 57 58] length of them
 16
index of the location [0]
inhabited locations
 [39 40 46 47 54] length of them
 5
index of the location [2]
inhabited locations
 [15 17 18 20 29] length of them
 5
index of the location [1]
inhabited locations
 [ 8  9 15 16 17 18 27 28] length of them
 8
index of the location [5]
inhabited locations
 [ 7 15 16 17 18] length of them
 5
index of the location [3]
inhabited locations
 [ 0  1  4 59 60 61 62] length of them
 7
index of the location [1]
inhabited locations
 [ 0  1  4 44 45 51 59 61 62] length of them
 9
index of the location [8]
inhabited locations
 [ 8 15 17 18 19 29] length of them
 6

In [20]:
for i in networkList:
    print('yeah!')
print(i)

yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
yeah!
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [19]:
full_IxS_collection = np.load(r'C:\Users\tjbro\Desktop\Thesis_Project\Thesis_code\10_by_50_by_20_by_10\numpy_arrays_of_VNE\IxS_iterating_through_all_3_knobs_where_location_10_individual_50_time_20_simulations_10.npy')
full_IxS_collection.shape

(10, 10, 10, 22, 20)

In [60]:
df1 = pd.read_csv(r'C:\Users\tjbro\Desktop\tab_list_.03\tab_list_.03_15')
df2 = pd.read_csv(r'C:\Users\tjbro\Desktop\tab_list_.03\tab_list_.03_253')
#display(df1.index.shape, df2.index.shape)
df2 = df2.set_index('Unnamed: 0')
del(df2.index.name)
columns = list(columns)
indexes = list(indexes)
# df1 = df1.loc[:, columns].fillna(0)
# df2 = df2.loc[:, columns].fillna(0)
#print(indexes, '\n', df2.index.values)
differentElements = set(indexes).difference(list(df2.index))
display(differentElements, list(differentElements))
#for i in differentElements:
numOfColumns = len(df2.columns.values)
print(numOfColumns)
randomlyAssigningMissingIndividuals = np.random.choice(numOfColumns, len(differentElements))
print(randomlyAssigningMissingIndividuals)
display(df2.shape)
for i in range(len(differentElements)):
    newRow = np.zeros(numOfColumns)
    newRow[randomlyAssigningMissingIndividuals[i]] = 1
    df2.loc[list(differentElements)[i]] = newRow
display(df2.shape)
df2
# display(df1.columns.shape, df2.columns.shape)
# display(df1.index.shape, df2.index.shape)

{41995, 42737, 42738, 42739}

[41995, 42737, 42738, 42739]

19
[ 6 14  6 13]

(25, 19)

(29, 19)

,23,41,57,58,73,74,75,76,108,138,149,155,156,167,168,169,185,186,187
35463,0.0,0.0,2.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35467,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
35480,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,12.0,0.0,0.0
39881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,8.0,0.0,0.0,0.0
39882,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,7.0,0.0,0.0,0.0
39883,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,7.0,0.0,0.0,0.0
39884,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0
39885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,7.0,0.0,0.0,0.0
39886,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,7.0
39887,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,20.0,0.0,0.0
39888,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11.0,1.0,9.0,0.0
41992,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0
41993,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0
41994,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0
42328,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42711,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42740,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42741,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42742,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0
42743,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42744,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0
42745,0.0,0.0,0.0,0.0,0.0,0.0,6.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42746,9.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41995,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42737,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
42738,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42739,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

# There are 29 unique individuals and 68 unique locations. 
Adding locations shouldn't be a problem when skewing the results, but adding a lot of individuals might...

In [65]:
display(df.head(5))
test_series = df.iloc[0]
test_series
nonzeroEntries = test_series.nonzero()
display(list(nonzeroEntries[0]))
df.iloc[0][4] = 1
df.head(5)

# The file is a list of tables so this function might be inapproppriate
# How to read an object from R dput to python.
#df = pd.read_csv(r'C:\Users\tjbro\Downloads\tab_list_.03')

,23,39,40,41,57,58,73,108,148,149,155,156,167,168,170,172,174,184,185,186
35463,0,0,2,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35467,0,0,0,0,0,0,0,0,0,0,2,2,0,0,3,3,0,0,0,0
35480,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
39879,0,0,0,0,0,0,0,0,1,11,0,0,12,0,0,0,0,0,0,0
39880,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,12,0

D:\Spyder\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  after removing the cwd from sys.path.

[2, 4, 5]

,23,39,40,41,57,58,73,108,148,149,155,156,167,168,170,172,174,184,185,186
35463,0,0,2,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35467,0,0,0,0,0,0,0,0,0,0,2,2,0,0,3,3,0,0,0,0
35480,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0
39879,0,0,0,0,0,0,0,0,1,11,0,0,12,0,0,0,0,0,0,0
39880,0,0,0,0,0,0,0,0,0,0,0,0,12,0,0,0,0,0,12,0

In [85]:
for i in df.index:
    testArray = df.loc[i]
    nonzeroEntries = testArray.nonzero()[0]
    array = []
    for j in nonzeroEntries:
        array.append(df.loc[i][j])
        df.loc[i][j] = 0
    #display(nonzeroEntries, array)
    df.loc[i][nonzeroEntries[np.argmax(array)]] = 1
#    display(df.loc[i])
df

D:\Spyder\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Series.nonzero() is deprecated and will be removed in a future version.Use Series.to_numpy().nonzero() instead
  This is separate from the ipykernel package so we can avoid doing imports until

,39,52,53,57,58,71,73,74,89,149,153,154,156,166,167,168,170,185,186,187
35463,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
35467,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
35480,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
39879,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
39880,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
39881,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
39882,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
39883,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
39884,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
39885,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
39886,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
39887,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
39888,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
41992,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
41993,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
41994,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
41995,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
42328,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42711,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42737,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
42738,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
42739,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
42740,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
42741,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42742,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
42743,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42744,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
42745,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
42746,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [3]:
df.head(10)

                   list(structure(c(2L   0L  0L.1  0L.2  0L.3  0L.4  0L.5  \
0L  0L  0L  0L  0L                  0L   1L    0L    0L    0L    0L    0L
                0L                  0L   0L    1L    0L    0L    0L    0L
                0L                  0L   0L    0L    0L    0L    3L    0L
                0L                  0L   0L    0L    0L    1L    0L    0L
                0L                  0L   0L    0L    0L    0L    0L    0L
                0L                  9L   0L    0L   12L    0L    0L    0L
                0L                  0L   0L    0L    0L    0L    0L    0L
                0L                  0L   0L    0L    0L    0L    0L    0L
                0L                  0L   0L    0L    0L    0L    0L    0L
1L  0L  0L  0L  0L                  0L   0L    0L    0L    0L    0L    0L

                    0L.6  0L.7  0L.8  0L.9
0L  0L  0L  0L  0L    0L    0L    0L    0L
                0L    0L    0L    0L    0L
                0L    0L    0L    0L    0L
                0L    0L    0L    0L    0L
                0L    0L    0L    0L    0L
                0L    2L    0L    0L        NaN
                0L    0L    0L    1L    0L
                0L    0L    0L    0L    2L
                0L    0L    0L    0L    0L
1L  0L  0L  0L  0L    0L    0L    0L    0L

In [6]:
df.shape

(2034, 12)

# Each row is a collar number and each column is a location

In [17]:
def addColumns(df, maxColumns):
    df = df.loc[:, maxColumns].fillna(0)
    return(df)